Added require

diff --git a/dig-deploy b/dig-deploy
--- a/dig-deploy
+++ b/dig-deploy
@@ -35,6 +35,14 @@ EOM
   exit 3
 }
 
+function require() {
+    command -v "$1" > /dev/null 2>&1 || {
+        echo "Some of the required cli command is not installed:"
+        echo "    please install $1" >&2;
+        exit 4;
+    }
+}
+
 [ $# == 0 ] && usage
 
 while [[ $# -gt 0 ]]
